import os

from dotenv import load_dotenv
from jira import JIRA

load_dotenv()


class JiraClient:
    def __init__(self):
        self.url = os.getenv("JIRA_URL")
        self.email = os.getenv("JIRA_EMAIL")
        self.api_token = os.getenv("JIRA_API_TOKEN")
        self.project_key = os.getenv("JIRA_PROJECT_KEY")
        self.board_id = os.getenv("JIRA_BOARD_ID")

        if not all([self.url, self.email, self.api_token, self.project_key]):
            self.jira = None
            print(
                "WARNING: Jira credentials not fully configured in .env. Defect creation disabled."
            )
        else:
            self.jira = JIRA(server=self.url, basic_auth=(self.email, self.api_token))

    def create_or_update_defect(
        self, test_name: str, error_message: str, traceback: str
    ):
        """
        Searches for an open Jira defect for this test.
        If found, adds a comment with the latest error.
        If not found, creates a new Bug ticket.
        """
        if not self.jira:
            return None

        # Jira JQL treats brackets and colons as reserved characters in text searches
        # We must escape them to find an exact match for Pytest parameter strings like "[chromium]"
        escaped_name = (
            test_name.replace("[", r"\\[").replace("]", r"\\]").replace(":", r"\\:")
        )

        # JQL Search string to find an open bug for this specific test
        summary_query = f'"Automated Test Failure: {escaped_name}"'
        jql = f"project = {self.project_key} AND summary ~ {summary_query} AND statusCategory != Done"

        try:
            issues = self.jira.search_issues(jql, maxResults=1)

            error_details = f"{{code:python}}\n{error_message}\n\n{traceback}\n{{code}}"

            if issues:
                # An open ticket already exists. Add a comment to deduplicate.
                issue = issues[0]
                comment_body = (
                    f"Test failed again during latest run.\n\n*Error:*\n{error_details}"
                )
                self.jira.add_comment(issue.key, comment_body)
                print(
                    f"[JIRA] Updated existing defect {issue.key} with latest failure."
                )
                return issue.key
            else:
                # No open ticket found. Create a new bug.
                issue_dict = {
                    "project": {"key": self.project_key},
                    "summary": f"Automated Test Failure: {test_name}",
                    "description": f"This defect was automatically generated by the Pytest framework.\n\n*Test Name:* {test_name}\n\n*Error Trace:*\n{error_details}",
                    "issuetype": {"name": "Bug"},
                }
                new_issue = self.jira.create_issue(fields=issue_dict)
                print(f"[JIRA] Created new defect {new_issue.key} for {test_name}.")

                # Move to active sprint if board_id is provided
                if self.board_id:
                    try:
                        sprints = self.jira.sprints(
                            board_id=int(self.board_id), state="active"
                        )
                        if sprints:
                            active_sprint = sprints[0]
                            self.jira.add_issues_to_sprint(
                                active_sprint.id, [new_issue.key]
                            )
                            print(
                                f"[JIRA] Moved {new_issue.key} to active Sprint: {active_sprint.name}"
                            )
                    except Exception as sprint_err:
                        print(
                            f"[JIRA WARNING] defect created but could not move to sprint: {sprint_err}"
                        )

                return new_issue.key

        except Exception as e:
            print(f"[JIRA ERROR] Could not create or update defect: {e}")
            return None
